### PR TITLE
First update to proposed data formats

### PR DESCRIPTION
**Pull request by nblettner**
- Changed naming conventions according to white paper draft

* Added two functions to opensense_data_downloader_and_transformer.py,
  * for assigning both global and variable specific attributes
  * for checking the existence of required variables

### CODE REVIEW

**Comment by cchwala** [comment]
@nblettner this line
```python
ds = oddt.check_existence_of_required_vars(ds)
```
because `ds` is `None` afterwards. Please fix.

**Comment by nblettner** [comment]
I changed  
> ```python
> ds = oddt.check_existence_of_required_vars(ds)
> ```
to 
```python
oddt.check_existence_of_required_vars(ds)
```

This function is only meant to print which of the required variables are missing. It may later be modified and used for testing. However, the present datasets do not all fulfill the requirements (see https://github.com/OpenSenseAction/OPENSENSE_sandbox/issues/16#issuecomment-1286721943).

I also adjusted the plotting of CML paths.

**Comment by cchwala** [comment]
thanks @nblettner 

Unfortunately the kernels dies each time when plotting the 6 CMLs from CZ when I run it in binder. I did some test and strangely the kernel dies at a different `i` each time in the for-loop.

I cannot image I way how your changes have led to this problem, but please check again.

**Comment by cchwala** [comment]
I did some more tests.

The kernel dies when doing this for the `ds_list` of the 6 Eband CMLs
```python
ds = ds_list[9]
ds.trsl.plot(x='time', figsize=(18, 2))
```

If done without the `x='time'`, it does plot correctly.

**Comment by nblettner** [comment]
In my tests (using binder), it first works fine. The kernel does not die no matter which element of `ds_list` I consider or whether or not I define `x='time'`. The memory limit is easily reached, though. If I rerun the following code 

```python
for i, ds in enumerate(ds_list):
    if i%2 == 0:
        fig, ax = plt.subplots(figsize=(18, 2))
    ds.tl.plot(x='time', ax=ax, label=f'{ds.frequency.values} GHz');
    plt.legend(loc=1)
```

several times, the memory increases, and eventually, the kernel also dies. This should, however, not be related to this PR, as I did not even add the attributes to those 6 Eband CMLs.


Apart from that, the code
> ds.trsl.plot(x='time', figsize=(18, 2)) 

should always return an error, since `trsl` has changed to `tl`.

**Comment by cchwala** [comment]
Indeed, memory consumption seems to be the issue. I ran the notebook in binder again and the kernel immediately died when looping and plotting the 6 CMLs.

The only solution that I see now, is to dump the parsed CML data to NetCDFs and then open them lazily afterwards to keep data on disc and not in RAM.

This has to be fixed because this basic example notebook should run without surprises for the user.

**Comment by cchwala** [comment]
Great! Thanks!

**Pull request merged**
