### PR TITLE
add a basic pycomlink example using OpenMRG data

### PR DESCRIPTION
**Pull request by maxmargraf**
As the title suggests the recent notebook is reworked to no feature an example routine to process the openMRG data with pycomlink.

### CODE REVIEW

**Comment by maxmargraf** [comment]
Notebook runs in mybinder without too much memory consumption.

**Comment by cchwala** [comment]
Small correction:

> TRSL is the transmitted signal level minus the received signal level and represents the total path loss along the CML

should be 

> TL (total path loss) is ...

Also, can you add a scatter plot or hexbin plot of the final result?

**Comment by maxmargraf** [comment]
@cchwala only saw your suggestion for the scatter plot now. I updated it with an hourly scatter plot for now.

**Comment by cchwala** [comment]
Thanks 👍

**Pull request merged**
