### PR TITLE
OpenMRG correct details in metadata

### PR DESCRIPTION
**Pull request by eoydvin**
Response to #67 

opensense_data_downloader_and_transformer: added comment indicating how the file was created. Conmverted frequency to MHz and length to meter. Add attributes after transform, so that they are not removed by the transform. Commented specification of "missing_value" in all attributes.

create_small_openMRG_example: Updated to add information on authors of the stored file and further info on resampling and interpolation of gaps. Removed encoding specifications so that xarray defaults to normal behaviour.

openMRG_use_case: updated to run with new nc file. transform frequency to GHz and length to km to make it work with pycomlink.

### CODE REVIEW

**Comment by eoydvin** [comment]
I'm not completely sure how to deal with missing values. In the current PR I have just removed any mentions on this, then xarray should default? But then what should be the requested value for [data_format_conventions](https://github.com/OpenSenseAction/OS_data_format_conventions/blob/main/netCDF_CML.adoc)?

Also not that in create_small_openMRG_example I removed most of the encoding specifications. @maxmargraf do you think the specifications should stay there?

**Comment by maxmargraf** [comment]
Regarding missing values, the white paper states the following: "The “missing _value” attribute is the conventional value of missing data. It is not set here, but the user should define it. The recommendation is to use, e.g., “NA” or “na”."

>Also not that in create_small_openMRG_example I removed most of the encoding specifications. @maxmargraf do you think the specifications should stay there?  
  

If the files stays within a certain file limit (I'd say a few MB), I do not think that we need encoding.

**Comment by eoydvin** [comment]
> Regarding missing values, the white paper states the following: "The “missing _value” attribute is the conventional value of missing data. It is not set here, but the user should define it. The recommendation is to use, e.g., “NA” or “na”."

So it should be specified in the transformer file? 

> If the files stays within a certain file limit (I'd say a few MB), I do not think that we need encoding.

Its 1,5 MB, so we could drop encoding.

**Comment by cchwala** [comment]
I recall that we had a discussion about that, maybe it was in offline in Krakow when we found that the attribute `missing_value` led to problems with writing to NetCDF, maybe because the actually required attribute `_FillValue` was not there.

See the CF conventions on missing data here: http://cfconventions.org/cf-conventions/cf-conventions.html#missing-data

**Comment by eoydvin** [comment]
Ok, I think I understand a bit more. Then, since the the opensense_data_downloader_and_transformer does not know what dataformat the user saves to (float, int etc), it should not specify _FillValue, as the fill value would depend on the final netcdf? Instead we could potentially define the _FillValue in the openMRG_use_case?

> Anyway, if you save floats to NetCDF the NaNs will just be saved as NaNs, right?
Jepp!

**Pull request merged**
