### PR TITLE
Show that RAINLINK v.1.3. runs

### PR DESCRIPTION
**Pull request by overeem11**

### CODE REVIEW

**Comment by overeem11** [comment]
This should be added to load RAINLINK automatically:
install.packages("RAINLINK_1.3.tar.gz", repos=NULL,type="source")

**Comment by cchwala** [comment]
If #30 works, this code
```
 install.packages("RAINLINK_1.3.tar.gz", repos=NULL,type="source")
```
could also be run automatically when binder is launched. But we will first have to see if it works to do that in some `post_build` process.

**Comment by cchwala** [comment]
I moved the changes of the env file to the env repo, see https://github.com/OpenSenseAction/OPENSENSE_sandbox_environment/pull/1/files

**Comment by cchwala** [comment]
thanks 👍

**Pull request merged**
