### PR TITLE
Add OpenMRG usecase

### PR DESCRIPTION
**Pull request by maxmargraf**
This PR is discussed in #49 
It adds
* one day of openMRG data from one sublink_id
* a notebook with as few steps as possible from raw CML data to a rainfall map
* an update of the index.ipynb to include this use case

### CODE REVIEW

**Comment by cchwala** [comment]
Thanks @maxmargraf. Looks already pretty good, and also very concise!

Some comments regarding the notebooks:
1. I suggest to put this use case as the first item in the index notebook since it is the one that people should check out first.
2. Can you show some 1h-maps, maybe 3x3 subplots (or an animation 😁 😇 ) of the resulting CML rainfall maps?
3. Yes, very short CMLs are still a mystery, or WAA is just higher than I expect. Have you tried with more WAA_max?
4. Any chance to add the radar data now for visual comparison?

**Comment by eoydvin** [comment]
There is a small conflict between the naming of polarization. pycomlink accepts 'v', 'V', and 'h', 'H', but the [recommended](https://github.com/OpenSenseAction/OS_data_format_conventions/blob/main/netCDF_CML.adoc) opensense format is 'vertical' and 'horizontal'. Its still a recommendation so I'm not so sure how much weight to put on this?

**Comment by maxmargraf** [comment]
I can include 1 and 2.
For 3, WAA probaly should be added based on length and the short ones defintely need more WAA, but thats probaly too much for a short example.
REgarding the reference, I tried different days and I could not find one with a at least ok looking match. The radar data is not the most trustworthy, short CMLs overestimate in the city center, while the few CMLs in the south also do not match the radar perfectly.. Here is one example for the 15 August: 
image

**Comment by maxmargraf** [comment]
`There is a small conflict between the naming of polarization. pycomlink accepts 'v', 'V', and 'h', 'H', but the [recommended](https://github.com/OpenSenseAction/OS_data_format_conventions/blob/main/netCDF_CML.adoc) opensense format is 'vertical' and 'horizontal'. Its still a recommendation so I'm not so sure how much weight to put on this?`
That is on the todo list for pycomlink. We will aim to use 'vertical' and 'horizontal' in the future.

**Comment by cchwala** [comment]
> I can include 1 and 2. For 3, WAA probaly should be added based on length and the short ones defintely need more WAA, but thats probaly too much for a short example. REgarding the reference, I tried different days and I could not find one with a at least ok looking match. The radar data is not the most trustworthy, short CMLs overestimate in the city center, while the few CMLs in the south also do not match the radar perfectly..

Okay. I see. Not easy to solve that now till tomorrow...

Maybe you could exclude the very short CMLs, maybe shorter than 500m or even shorter then 1000m, in particular if they have frequencies below 30 GHz?

**Comment by maxmargraf** [comment]
> Maybe you could exclude the very short CMLs, maybe shorter than 500m or even shorter then 1000m, in particular if they have frequencies below 30 GHz?  
  
That is almost what the map above already shows  - removing CMLs which are either shorter than 1km, show more than 200 mm/d on that day or without rainfall in the whole three month period.

**Comment by maxmargraf** [comment]
Updated the notebook including the comments from @cchwala [above](https://github.com/OpenSenseAction/OPENSENSE_sandbox/pull/56#issuecomment-1609060545).
I did not add an animation, combining `pcolormesh` with `matplotlib.animation` as well as adding a CML line plot is a bit tricky. But there should definitley be a solution similar to the example shown here: https://gist.github.com/tenomoto/dc7ff221c832db4c90832eb21f4b2f48#file-animation-ipynb

**Comment by cchwala** [comment]
Thank again! 👍 
I am merging this now 🎉 🚀 

We can discuss offline some potential small improvements that can be done later.

**Pull request merged**
