### PR TITLE
add code and example of PWSQC

### PR DESCRIPTION
**Pull request by LottedeVos**
I have tried to add the packages needed for the PWSQC method. I have duplicated the style of the other R-packages by prefixing "- r-", although I'm not sure that is correct. 
The required R-packages from CRAN are: 
data.table (for preprocessing in PWSQC_0.R)
geosphere (for PWSQC_1)
sf (for PWSQC_1_alternativeversion.R)
s1 (for PWSQC_1_alternativeversion.R)
TeachingDemos (for visualization in PWSQC_4.R)

### CODE REVIEW

**Review by fenclmar — CHANGES_REQUESTED** [review]
Push it again when it is ready

**Comment by cchwala** [comment]
@LottedeVos Thanks for the update. I am not familier with R notebooks, though. How does one run the code in the binder? Do I need to run the rmd file in RStudio? If I try that, I get a lot of errors. I guess I am doing something wrong.

**Comment by LottedeVos** [comment]
Hello @cchwala, to be honest I'm not quite sure. I worked out the way to connect the R notebook to github with Martin, @fenclmar, do you know how to run the code now that it is pushed?

**Comment by maxmargraf** [comment]
`PWSQC_minimal_example.ipynb` is now providing a minimal running example of the HI and VI flagging from PWSQC with some visualization. At the moment no code from the submodule is used and the complete notebook including the SO flagging is WIP. The main reason for this is the long runtime of the SO flagging. We now have two option IMHO: 1) merge as is and used the minimal example as showcase during the meeting or 2) remove the WIP files for the moment to have an "as-clean-as-possible" repo and work on it in a new PR.

**Comment by LottedeVos** [comment]
Thank Max! Both options would work but I'd prefer to keep the allscripts version available as this may give insight in the SOfilter and biascorrection.

**Comment by cchwala** [comment]
Thanks @LottedeVos and @maxmargraf 

I will merge it now as is to have all showcases combined in the main branch as a demo for today's meeting. We can iterate further in a new PR.

**Pull request merged**
